/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppCalendarioRouteImport } from './routes/_app.calendario'
import { Route as AppClinicasRouteImport } from './routes/_app.clinicas'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppNovaOrdemRouteImport } from './routes/_app.nova-ordem'
import { Route as AppOrdensIdRouteImport } from './routes/_app.ordens.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicasRoute = AppClinicasRouteImport.update({
  id: '/clinicas',
  path: '/clinicas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaOrdemRoute = AppNovaOrdemRouteImport.update({
  id: '/nova-ordem',
  path: '/nova-ordem',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensIdRoute = AppOrdensIdRouteImport.update({
  id: '/ordens/$id',
  path: '/ordens/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/calendario': typeof AppCalendarioRoute
  '/clinicas': typeof AppClinicasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/nova-ordem': typeof AppNovaOrdemRoute
  '/ordens/$id': typeof AppOrdensIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/calendario': typeof AppCalendarioRoute
  '/clinicas': typeof AppClinicasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/nova-ordem': typeof AppNovaOrdemRoute
  '/ordens/$id': typeof AppOrdensIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/clinicas': typeof AppClinicasRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/nova-ordem': typeof AppNovaOrdemRoute
  '/_app/ordens/$id': typeof AppOrdensIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendario'
    | '/clinicas'
    | '/configuracoes'
    | '/dashboard'
    | '/nova-ordem'
    | '/ordens/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/calendario'
    | '/clinicas'
    | '/configuracoes'
    | '/dashboard'
    | '/nova-ordem'
    | '/ordens/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/calendario'
    | '/_app/clinicas'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/nova-ordem'
    | '/_app/ordens/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clinicas': {
      id: '/_app/clinicas'
      path: '/clinicas'
      fullPath: '/clinicas'
      preLoaderRoute: typeof AppClinicasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nova-ordem': {
      id: '/_app/nova-ordem'
      path: '/nova-ordem'
      fullPath: '/nova-ordem'
      preLoaderRoute: typeof AppNovaOrdemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens/$id': {
      id: '/_app/ordens/$id'
      path: '/ordens/$id'
      fullPath: '/ordens/$id'
      preLoaderRoute: typeof AppOrdensIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppClinicasRoute: typeof AppClinicasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNovaOrdemRoute: typeof AppNovaOrdemRoute
  AppOrdensIdRoute: typeof AppOrdensIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarioRoute: AppCalendarioRoute,
  AppClinicasRoute: AppClinicasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNovaOrdemRoute: AppNovaOrdemRoute,
  AppOrdensIdRoute: AppOrdensIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
