/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PigattoRouteImport } from './routes/pigatto'
import { Route as PatriotaRouteImport } from './routes/patriota'
import { Route as PatriotaGerarRouteImport } from './routes/patriota-gerar'
import { Route as AppCalendarioRouteImport } from './routes/_app.calendario'
import { Route as AppClinicasRouteImport } from './routes/_app.clinicas'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppVisaoRouteImport } from './routes/_app.visao'
import { Route as AppExpedicaoRouteImport } from './routes/_app.expedicao'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppOsRouteImport } from './routes/_app.os'
import { Route as AppNovaOrdemRouteImport } from './routes/_app.nova-ordem'
import { Route as AppOrdensIdRouteImport } from './routes/_app.ordens.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PigattoRoute = PigattoRouteImport.update({
  id: '/pigatto',
  path: '/pigatto',
  getParentRoute: () => rootRouteImport,
} as any)
const PatriotaRoute = PatriotaRouteImport.update({
  id: '/patriota',
  path: '/patriota',
  getParentRoute: () => rootRouteImport,
} as any)
const PatriotaGerarRoute = PatriotaGerarRouteImport.update({
  id: '/patriota-gerar',
  path: '/patriota-gerar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicasRoute = AppClinicasRouteImport.update({
  id: '/clinicas',
  path: '/clinicas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppVisaoRoute = AppVisaoRouteImport.update({
  id: '/visao',
  path: '/visao',
  getParentRoute: () => AppRoute,
} as any)
const AppExpedicaoRoute = AppExpedicaoRouteImport.update({
  id: '/expedicao',
  path: '/expedicao',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppOsRoute = AppOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaOrdemRoute = AppNovaOrdemRouteImport.update({
  id: '/nova-ordem',
  path: '/nova-ordem',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensIdRoute = AppOrdensIdRouteImport.update({
  id: '/ordens/$id',
  path: '/ordens/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pigatto': typeof PigattoRoute
  '/patriota': typeof PatriotaRoute
  '/patriota-gerar': typeof PatriotaGerarRoute
  '/calendario': typeof AppCalendarioRoute
  '/clinicas': typeof AppClinicasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/visao': typeof AppVisaoRoute
  '/expedicao': typeof AppExpedicaoRoute
  '/analytics': typeof AppAnalyticsRoute
  '/os': typeof AppOsRoute
  '/nova-ordem': typeof AppNovaOrdemRoute
  '/ordens/$id': typeof AppOrdensIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pigatto': typeof PigattoRoute
  '/patriota': typeof PatriotaRoute
  '/patriota-gerar': typeof PatriotaGerarRoute
  '/calendario': typeof AppCalendarioRoute
  '/clinicas': typeof AppClinicasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/visao': typeof AppVisaoRoute
  '/expedicao': typeof AppExpedicaoRoute
  '/analytics': typeof AppAnalyticsRoute
  '/os': typeof AppOsRoute
  '/nova-ordem': typeof AppNovaOrdemRoute
  '/ordens/$id': typeof AppOrdensIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pigatto': typeof PigattoRoute
  '/patriota': typeof PatriotaRoute
  '/patriota-gerar': typeof PatriotaGerarRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/clinicas': typeof AppClinicasRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/visao': typeof AppVisaoRoute
  '/_app/expedicao': typeof AppExpedicaoRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/os': typeof AppOsRoute
  '/_app/nova-ordem': typeof AppNovaOrdemRoute
  '/_app/ordens/$id': typeof AppOrdensIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pigatto'
    | '/patriota'
    | '/patriota-gerar'
    | '/calendario'
    | '/clinicas'
    | '/configuracoes'
    | '/dashboard'
    | '/visao'
    | '/expedicao'
    | '/analytics'
    | '/os'
    | '/nova-ordem'
    | '/ordens/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pigatto'
    | '/patriota'
    | '/patriota-gerar'
    | '/calendario'
    | '/clinicas'
    | '/configuracoes'
    | '/dashboard'
    | '/visao'
    | '/expedicao'
    | '/analytics'
    | '/os'
    | '/nova-ordem'
    | '/ordens/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/pigatto'
    | '/patriota'
    | '/patriota-gerar'
    | '/_app/calendario'
    | '/_app/clinicas'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/visao'
    | '/_app/expedicao'
    | '/_app/analytics'
    | '/_app/os'
    | '/_app/nova-ordem'
    | '/_app/ordens/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PigattoRoute: typeof PigattoRoute
  PatriotaRoute: typeof PatriotaRoute
  PatriotaGerarRoute: typeof PatriotaGerarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pigatto': {
      id: '/pigatto'
      path: '/pigatto'
      fullPath: '/pigatto'
      preLoaderRoute: typeof PigattoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patriota': {
      id: '/patriota'
      path: '/patriota'
      fullPath: '/patriota'
      preLoaderRoute: typeof PatriotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patriota-gerar': {
      id: '/patriota-gerar'
      path: '/patriota-gerar'
      fullPath: '/patriota-gerar'
      preLoaderRoute: typeof PatriotaGerarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clinicas': {
      id: '/_app/clinicas'
      path: '/clinicas'
      fullPath: '/clinicas'
      preLoaderRoute: typeof AppClinicasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visao': {
      id: '/_app/visao'
      path: '/visao'
      fullPath: '/visao'
      preLoaderRoute: typeof AppVisaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expedicao': {
      id: '/_app/expedicao'
      path: '/expedicao'
      fullPath: '/expedicao'
      preLoaderRoute: typeof AppExpedicaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/os': {
      id: '/_app/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof AppOsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nova-ordem': {
      id: '/_app/nova-ordem'
      path: '/nova-ordem'
      fullPath: '/nova-ordem'
      preLoaderRoute: typeof AppNovaOrdemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens/$id': {
      id: '/_app/ordens/$id'
      path: '/ordens/$id'
      fullPath: '/ordens/$id'
      preLoaderRoute: typeof AppOrdensIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppClinicasRoute: typeof AppClinicasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppVisaoRoute: typeof AppVisaoRoute
  AppExpedicaoRoute: typeof AppExpedicaoRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppOsRoute: typeof AppOsRoute
  AppNovaOrdemRoute: typeof AppNovaOrdemRoute
  AppOrdensIdRoute: typeof AppOrdensIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarioRoute: AppCalendarioRoute,
  AppClinicasRoute: AppClinicasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppVisaoRoute: AppVisaoRoute,
  AppExpedicaoRoute: AppExpedicaoRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppOsRoute: AppOsRoute,
  AppNovaOrdemRoute: AppNovaOrdemRoute,
  AppOrdensIdRoute: AppOrdensIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PigattoRoute: PigattoRoute,
  PatriotaRoute: PatriotaRoute,
  PatriotaGerarRoute: PatriotaGerarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
